### ISSUE TITLE
Add `kata-acrn` to the runtimes pre-configured for Docker

### ISSUE THREAD

**Issue by gvancuts** [kata-containers/packaging#1078] opened 2020-06-16 18:27 UTC
**Which feature do you think can be improved?**

`kata-deploy-docker` configures Docker with a number of runtimes, 4 in total. ACRN is not in the list at the moment.

**How can it be improved?**

We can add a `kata-acrn` runtime to Docker's `/etc/docker/daemon.json` file. The `toml` file is already installed by default.

**Additional Information**

No

**Comment by ariel-adam** [comment] 2020-12-08 16:28
Closing this issue since the problem is fixed however the PR in 1.x was pointed to the wrong issue.

**Comment by ariel-adam** [comment] 2020-12-08 16:29
#1077

**Closed** 2020-12-08 16:29 UTC
Labels: good-first-issue
