### ISSUE TITLE
kata-runtime installation fails

### ISSUE THREAD

**Issue by guoruijing** [kata-containers/packaging#322] opened 2019-01-30 00:45 UTC
worker2:  kata-runtime : Depends: qemu-lite (>= 2.11.0+git.f886228-56) but 2.11.0+git.87517afd72-57 is to be installed
    worker2: E: Unable to correct problems, you have held broken packages.
==> worker2: An error occurred. The error will be shown after all tasks complete.

**Comment by egernst** [comment] 2019-01-30 03:37
@bergwolf  have you seen this?

@guoruijing  what distro are you on?

**Comment by guoruijing** [comment] 2019-01-30 05:34
I used Ubuntu 16.04. this is regression.

**Comment by grahamwhaley** [comment] 2019-01-30 09:54
That feels very related to the open issue https://github.com/kata-containers/runtime/issues/1184 ?

**Comment by jodh-intel** [comment] 2019-01-30 11:02
@guoruijing - thanks for reporting. But we really could benefit from a little more details here:

- What version of Kata were you using before the install failed?
- Can we see more complete logs please?

I've just tried installing Kata on 16.04 using https://github.com/kata-containers/documentation/blob/master/install/installing-with-kata-manager.md and it's working fine. Hence, the problem is presumably an update issue.

Another data point and more proof that we need to implement https://github.com/kata-containers/ci/issues/10 asap though.

**Comment by guoruijing** [comment] 2019-01-31 02:32
the package came from http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04/

kata-runtime_1.4.0+git.21f0059-55_amd64.deb
kata-proxy_1.4.0+git.e1856c2-40_amd64.deb
qemu-lite_2.11.0+git.87517afd72-57_amd64.deb

**Comment by marcov** [comment] 2019-01-31 10:30
Hi, the problem here is that, in the `release` project, [{runtime, shim, proxy} fail to build](https://build.opensuse.org/project/monitor/home:katacontainers:release?arch_x86_64=1&defaults=0&failed=1&repo_xUbuntu_16_04=1) for Ubuntu 16.04. We had the same in use in `releases:x86_64:master`, and it was fixed by setting up the project config so that a more recent GCC version was picked when building packages.

In the future, to avoid these kind of situations, new releases should first be tested in temporary project branches on OBS, then submitted to the official OBS project and finally accepted / rejected for merge by reviewers. That's what we do with all the openSUSE packages.

> I remember there were discussion about releases vs. release before. Which one did we decide to use? cc @marcov

It's discussed [here](kata-containers/runtime#1184). If there isn't a strong reason to keep `release` around, we should nuke it.

**Closed** 2021-04-07 09:01 UTC
